#!/usr/bin/env python
"""Generate stage-2 scoring configs, one CV file per model block.

`run_compare`'s `kb_dir` is scored in full with the oracle and bias of the block it
appears under, and the block's `name` is only a label — it filters nothing. Pointing
`kb_dir` at a directory therefore scores every knowledge base in it against ONE
model's ground truth, silently: the files gain evaluation blocks, nothing errors, and
the numbers are wrong for every model but the one named. That happened on 2026-08-27
and cost 79 corrupted files, recovered from git.

`find_cv_files` accepts a single file, so each CV file gets its own block with its own
oracle and bias. The mapping comes from the filename's model stem, which is how the
sweep named them.

    make_score_configs.py --out data/results_sosym/compare_configs
    make_score_configs.py --out ... --kbs arcade-game     # one KB, to measure cost
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

# Longest first: REAL-FM-7 must not match inside another stem.
STEMS = ['busybox-1.18.0', 'arcade-game', 'REAL-FM-7', 'REAL-FM-4', 'fqa']

HEADER = """# Generated by tools/sosym_r1/make_score_configs.py -- do not edit by hand.
# One block per CV file. run_compare scores an entire kb_dir with the oracle of the
# block it sits under, so a block per FILE is what keeps each knowledge base scored
# against its own ground truth.
[general]
output_dir = "data/results_sosym"
verbose = false

[compare]
strategy = "all"
"""

BLOCK = """
[[models]]
name = "{name}"
oracle = "data/fms/{stem}.uvl"
bias = "data/bias/{stem}-bias.json"
kb_dir = "{cv_file}"
"""


def stem_of(filename: str) -> str | None:
    for stem in STEMS:
        if filename.startswith(stem + '_'):
            return stem
    return None


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--out', required=True)
    ap.add_argument('--cv-dir',
                    help="score CV files under this directory instead of "
                         "data/results_sosym/<algorithm>/. Searched recursively, so it "
                         "accepts the one-directory-per-cell layout a scratch re-run "
                         "produces. Paths are written absolute — a scratch tree is not "
                         "under the repo, so a repo-relative path would not resolve.")
    ap.add_argument('--kbs', nargs='+', help="restrict to these model stems")
    ap.add_argument('--algorithms', nargs='+', default=['congen', 'interactive'])
    args = ap.parse_args()

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []

    for algorithm in args.algorithms:
        if args.cv_dir:
            src = Path(args.cv_dir)
            candidates = sorted(src.rglob(f'*_cv_*.json'))
            # rglob crosses every algorithm's directory at once; keep this block's own.
            candidates = [c for c in candidates if c.parent.name == algorithm]
        else:
            src = REPO / 'data' / 'results_sosym' / algorithm
            candidates = sorted(src.glob('*_cv_*.json')) if src.is_dir() else []
        if not candidates:
            continue
        for cv in candidates:
            stem = stem_of(cv.name)
            if stem is None:
                print(f"  SKIP, no stem matched: {cv.name}", file=sys.stderr)
                continue
            if args.kbs and stem not in args.kbs:
                continue
            written.append((algorithm, stem, cv))

    if not written:
        print("no CV files matched", file=sys.stderr)
        return 1

    by_algo: dict = {}
    for algorithm, stem, cv in written:
        by_algo.setdefault(algorithm, []).append((stem, cv))

    for algorithm, rows in by_algo.items():
        text = HEADER
        for stem, cv in rows:
            # resolve() FIRST. rglob over a relative --cv-dir yields relative paths,
            # and relative_to(REPO) against an absolute REPO then raises, falling
            # through to an absolute path that hardcodes one machine's checkout. That
            # is how score_interactive.toml came to carry 56 such paths while every
            # config generated before it was relative. A tree inside the repo must
            # emit a repo-relative path whatever form the caller passed.
            try:
                path = cv.resolve().relative_to(REPO)
            except ValueError:
                path = cv.resolve()          # genuinely outside the repo: a scratch tree
            text += BLOCK.format(name=cv.stem, stem=stem, cv_file=path)
        path = out_dir / f"score_{algorithm}.toml"
        path.write_text(text)
        print(f"  {path}: {len(rows)} blocks")

    print(f"\n{len(written)} CV files will be scored, each against its own oracle")
    return 0


if __name__ == '__main__':
    sys.exit(main())
