#!/usr/bin/env python
"""Run the SoSyM sweep in windows, losing at most the unit that was running.

The machine moves between a work window and a home window and the lid closes at
16:00, so the runner takes the window it has -- ``--budget 5.5h`` -- and starts a
unit only when the unit plausibly fits what is left. When nothing fits it exits
cleanly rather than starting something that will be killed.

Every estimate in ``sweep_units`` is a floor derived from a different algorithm's
measurements, so the budget check multiplies by a safety factor and, once step 2
has measured it, by a calibrated ConGen/condition-A ratio. The point is not to
predict a unit's cost but to make a wrong prediction harmless.

    sweep_queue.py init                     build the ledger
    sweep_queue.py status                   what is done, what is left
    sweep_queue.py run --budget 5.5h        work the queue for one window

Units are ledger rows; a row goes to ``done`` only after its partial is on disk
and newer than the moment the unit started, so a crashed run cannot be recorded
as a success.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import sweep_units as units_mod  # noqa: E402

REPO = Path(__file__).resolve().parents[2]
LEDGER = REPO / 'tools' / 'sosym_r1' / 'sweep-ledger.json'
LEDGER_SCHEMA = 'acqmss.sweep.ledger/1'
DEFAULT_OUTPUT_ROOT = 'data/results_sosym'
SAFETY_FACTOR = 1.5
# Per-fold wall-clock guard for QuAcq, in seconds. Generous by design: it must never
# be the thing that stops a fold, because a wall-clock bound is machine-dependent and
# nothing reported may rest on it. If it fires, that is a defect to investigate, not
# a result to report.
WALL_CLOCK_GUARD_S = 6 * 3600

CONFIG_TEMPLATE = """# Generated by tools/sosym_r1/sweep_queue.py -- do not edit by hand.
[general]
seed = 42
output_dir = "SWEEP_ALWAYS_PASSES_-o"
verbose = false

[evaluation]
algorithm = "{algorithm}"
n_folds = {n_folds}
solver_name = "glucose4"
solver_mode = "{solver_mode}"
shuffle_bias = true

[evaluation.interactive]
# max_queries is the stopping RULE: deterministic, machine-independent, reportable.
# timeout_s is an operational GUARD so one pathological fold cannot hold a window
# open. It records convergence_reason='timeout', distinct from 'max_queries'. If it
# ever fires, that fold's numbers are not comparable and the window report says so.
max_queries = {max_queries}
timeout_s = {timeout_s}
query_mode = "{query_mode}"

[[models]]
name = "{model}"
oracle = "data/fms/{stem}.uvl"
bias = "data/bias/{stem}-bias.json"
examples = "data/examples/{model}.json"
folds_path = "data/folds/{model}_folds.json"
"""


def now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec='seconds')


def parse_budget(text: str) -> float:
    """'5.5h' / '90m' / '5400s' -> hours."""
    m = re.fullmatch(r'\s*([0-9]*\.?[0-9]+)\s*([hms])\s*', text, re.I)
    if not m:
        raise SystemExit(f"--budget expects a value like 5.5h, 90m or 5400s; got {text!r}")
    value, unit = float(m.group(1)), m.group(2).lower()
    return value * {'h': 1.0, 'm': 1 / 60, 's': 1 / 3600}[unit]


def write_ledger(ledger: dict, path: Path, own_metadata: bool = False) -> None:
    """Atomic, and it does not clobber metadata edited while a window ran.

    A window loads the ledger once and rewrites it after every unit, so anything
    edited on disk in the meantime -- a calibration reworded, a note added, an
    exclusion recorded -- was silently reverted the next time a unit finished. That
    happened on 2026-08-23 and cost a committed evidence edit with no error to show
    for it. A running window owns ``units`` and nothing else; every other key is
    re-read from disk at write time.

    ``own_metadata`` is for the one caller that legitimately writes the whole
    document: ``init``, which is creating or deliberately rebuilding it.
    """
    payload = ledger
    if not own_metadata and path.exists():
        try:
            on_disk = json.loads(path.read_text())
        except (json.JSONDecodeError, OSError):
            on_disk = {}
        payload = {k: v for k, v in on_disk.items() if k != 'units'}
        for key, value in ledger.items():
            payload.setdefault(key, value)
        payload['units'] = ledger['units']
    tmp = path.with_suffix(path.suffix + '.tmp')
    tmp.write_text(json.dumps(payload, indent=2) + "\n")
    tmp.replace(path)


def load_ledger(path: Path) -> dict:
    if not path.exists():
        raise SystemExit(f"no ledger at {path} -- run "
                         f"`python3 tools/sosym_r1/sweep_queue.py init` first")
    ledger = json.loads(path.read_text())
    if ledger.get('schema') != LEDGER_SCHEMA:
        raise SystemExit(f"{path}: ledger schema {ledger.get('schema')!r}, expected {LEDGER_SCHEMA!r}")
    return ledger


def current_commit() -> str | None:
    try:
        return subprocess.run(['git', 'rev-parse', 'HEAD'], cwd=REPO, check=True,
                              capture_output=True, text=True).stdout.strip()
    except (subprocess.CalledProcessError, OSError):
        return None


def cmd_init(args) -> int:
    path = Path(args.ledger)
    if path.exists() and not args.force:
        raise SystemExit(f"{path} exists; pass --force to rebuild (this discards progress)")
    ledger = {
        'schema': LEDGER_SCHEMA,
        'created_utc': now(),
        'output_root': args.output_root,
        'n_folds': units_mod.N_FOLDS,
        'safety_factor': SAFETY_FACTOR,
        # Step 2 writes these: every estimate below is a condition-A (AcqMss only)
        # floor, and ConGen is AcqMss plus Reduce. Until measured, None means the
        # safety factor alone stands between an estimate and a killed unit.
        'congen_multiplier': None,
        'multiplier_evidence': None,
        'excluded': {
            'busybox-1.18.0_rs_2n': 'bounded not completed: ~317 h for three folds',
            'busybox-1.18.0_rs_3n': 'bounded not completed: ~745 h for three folds',
            'ea2468': 'excluded from the evaluation tables',
            'QuAcq-active': 'not run (SoSyM revision doc, section 7 C1, decision 1)',
        },
        'units': units_mod.build_units(),
    }
    write_ledger(ledger, path, own_metadata=True)
    print(f"wrote {path}: {len(ledger['units'])} units")
    cmd_status(argparse.Namespace(ledger=args.ledger))
    return 0


def cmd_status(args) -> int:
    ledger = load_ledger(Path(args.ledger))
    by_status: dict = {}
    for unit in ledger['units']:
        by_status.setdefault(unit['status'], []).append(unit)
    print(f"ledger: {args.ledger}")
    print(f"output root: {ledger['output_root']}   "
          f"multiplier: {ledger['congen_multiplier'] or 'UNCALIBRATED'}   "
          f"safety: x{ledger['safety_factor']}")
    for status in sorted(by_status):
        rows = by_status[status]
        est = sum(u['estimate_h'] for u in rows if u['estimate_h'] is not None)
        act = sum(u['actual_h'] for u in rows if u['actual_h'] is not None)
        extra = f", actual {act:.2f} h" if act else ""
        print(f"  {status:12s} {len(rows):4d} units   estimate {est:7.2f} h{extra}")
    done = by_status.get('done', [])
    # `is not None`, not truthiness: a condition-A reference of 0.0000 h is a real
    # measurement of a sub-millisecond cell, not missing data. It still cannot carry
    # a ratio, so it is excluded from the mean and counted out loud rather than
    # vanishing into a denominator nobody checks.
    # The ratio means one thing: ConGen against AcqMss condition A. A unit whose
    # estimate is a nominal placeholder, or whose algorithm is not ConGen, has no
    # condition-A reference to be a ratio *of* -- including it would report a
    # measurement against a number nobody measured.
    measured = [u for u in done
                if u['actual_h'] is not None and u['estimate_h'] is not None
                and u.get('estimate_source', 'condition-A') == 'condition-A'
                and u['algorithm'] == 'congen']
    paired = [(u['estimate_h'], u['actual_h']) for u in measured if u['estimate_h'] > 0]
    if paired:
        ratio = sum(a for _, a in paired) / sum(e for e, _ in paired)
        print(f"  ConGen vs condition A: {ratio:.2f}x over {len(paired)} of "
              f"{len(done)} done units")
        skipped = len(done) - len(paired)
        if skipped:
            print(f"    ({skipped} done units carry no ratio: zero, nominal or "
                  f"non-ConGen reference)")

    # Last line, and deliberately so: a truncated read of this output must still be
    # true. The counts above are per-bucket and easy to mistake for a total -- this
    # one cannot be, and it is the line to trust for whether a cell exists.
    # Every status that exists is named, in a stable order, with unknown ones
    # appended rather than dropped. A hardcoded list would silently omit a status
    # added later -- which is the same shape as the bug this line exists to fix.
    known = ('done', 'running', 'pending', 'failed', 'long-run', 'no-estimate')
    order = [k for k in known if k in by_status] + sorted(set(by_status) - set(known))
    summary = ", ".join(f"{len(by_status[k])} {k}" for k in order)
    total = len(ledger['units'])
    assert sum(len(by_status[k]) for k in order) == total, "status buckets lost a unit"
    print(f"TOTAL {total} units: {summary}")
    return 0


def cmd_reestimate(args) -> int:
    """Refresh estimates without touching progress.

    Estimates get revised -- a reference is re-read, a cell is measured for the
    first time -- and rebuilding the ledger to pick that up would discard the
    record of every unit already paid for. Only ``estimate_h`` moves here, and a
    unit that was parked for want of an estimate is released once it has one.
    """
    ledger_path = Path(args.ledger)
    # Refuse while a window runs. A window loads `units` once and rewrites them after
    # every unit, so an estimate written here mid-window is reverted the next time a
    # unit finishes — silently, with the file looking correct in between. That happened
    # on 2026-08-25: 72 example_first estimates set at 12:55 were gone by 16:17, and the
    # only symptom was a no-estimate count that had grown instead of shrunk.
    # write_ledger's metadata merge does not help here: `units` is the window's to own.
    lock = ledger_path.with_suffix('.lock')
    if lock.exists():
        try:
            pid = int(json.loads(lock.read_text())['pid'])
            os.kill(pid, 0)
        except (json.JSONDecodeError, OSError, KeyError, ValueError, ProcessLookupError):
            print(f"  ignoring a stale lock at {lock}")
        else:
            raise SystemExit(
                f"a window is running (pid {pid}); it owns the units array and would "
                f"revert this. Re-estimate after it closes.")

    ledger = load_ledger(ledger_path)
    fresh = {u['id']: u for u in units_mod.build_units()}

    changed = 0
    for unit in ledger['units']:
        new_unit = fresh.get(unit['id'])
        if new_unit is None or new_unit['estimate_h'] == unit['estimate_h']:
            continue
        unit['estimate_h'] = new_unit['estimate_h']
        # Status is progress, not estimate -- but the two statuses that exist
        # *because* of an estimate follow it.
        if unit['status'] in (units_mod.STATUS_PENDING, units_mod.STATUS_LONG_RUN,
                              units_mod.STATUS_NO_ESTIMATE):
            unit['status'] = new_unit['status']
        changed += 1

    write_ledger(ledger, ledger_path)
    print(f"re-estimated {changed} units")
    return cmd_status(args)


def unit_config(ledger: dict, unit: dict, max_queries: int) -> Path:
    """One generated config per cell, written under the output root."""
    root = REPO / ledger['output_root'] / 'configs'
    root.mkdir(parents=True, exist_ok=True)
    model = f"{unit['kb_stem']}_{unit['sampling']}"
    suffix = f"_{unit['query_mode']}" if unit['query_mode'] else ""
    path = root / f"{unit['algorithm']}{suffix}_{model}.toml"
    path.write_text(CONFIG_TEMPLATE.format(
        algorithm=unit['algorithm'], n_folds=ledger['n_folds'],
        solver_mode=unit['solver_mode'], max_queries=max_queries,
        query_mode=unit['query_mode'] or 'example_only',
        timeout_s=WALL_CLOCK_GUARD_S,
        model=model, stem=unit['kb_stem']))
    return path


def fold_stop_reason(partial: Path) -> str | None:
    """Why this fold stopped, when the algorithm records it (interactive only)."""
    try:
        return json.loads(partial.read_text())['fold'].get('convergence_reason')
    except (json.JSONDecodeError, OSError, KeyError):
        return None


def budgeted_cost(ledger: dict, unit: dict) -> float:
    """What the budget check charges for a unit, in hours.

    The multiplier is per knowledge base, and a knowledge base with no measurement
    of its own charges the full condition-A estimate. The handoff expected one
    global ratio above 1 -- ConGen being AcqMss plus Reduce -- but measurement went
    the other way (0.11x-0.50x across four knowledge bases), so the ratio is
    evidence rather than a correction, and evidence does not transfer to a
    knowledge base 60x larger than any of the ones it was gathered on. Each KB's
    own worst observed cell is used, not its median, and the safety factor still
    applies on top.
    """
    multipliers = ledger.get('congen_multiplier') or {}
    if not isinstance(multipliers, dict):  # pre-per-KB ledger
        multipliers = {}
    # The multiplier is the measured ConGen/condition-A ratio and means nothing for
    # any other algorithm. Applying it to a QuAcq unit would scale its estimate by a
    # number derived from a different computation — and for busybox it would scale it
    # DOWN by 5x, which is the dangerous direction.
    multiplier = (multipliers.get(unit['kb'], multipliers.get('default', 1.0))
                  if unit['algorithm'] == 'congen' else 1.0)
    return unit['estimate_h'] * multiplier * ledger['safety_factor']


def run_unit(ledger: dict, unit: dict, ledger_path: Path, max_queries: int) -> bool:
    """Run one fold in its own process. Returns True when the partial is durable.

    One process per fold is deliberate and not just a consequence of the queue:
    ``memory_peak_mb`` is a tracemalloc peak that tracks the fold's position in its
    process, so batching folds would make the reported memory depend on how the
    windows happened to fall.
    """
    config = unit_config(ledger, unit, max_queries)
    out_dir = REPO / ledger['output_root']
    partial = (out_dir / unit['algorithm'] / 'partials' / unit['partial'])

    unit['status'] = 'running'
    unit['started_utc'] = now()
    unit['commit'] = current_commit()
    write_ledger(ledger, ledger_path)

    started = time.time()
    proc = subprocess.run(
        [sys.executable, '-m', 'apps.run_cv', str(config), '-o', str(out_dir),
         '--folds', str(unit['fold'])],
        cwd=REPO, capture_output=True, text=True)
    elapsed_h = (time.time() - started) / 3600

    # Durability, not exit status: a unit counts as done only if its partial is on
    # disk and was written by this run. An exit code of 0 from a run that produced
    # nothing would otherwise be recorded as a completed unit.
    durable = partial.exists() and partial.stat().st_mtime >= started

    unit['actual_h'] = round(elapsed_h, 4)
    unit['finished_utc'] = now()
    if durable and proc.returncode == 0:
        unit['status'] = 'done'
        # If the wall-clock guard fired, this fold stopped for a machine-dependent
        # reason and its budget numbers are not comparable with the others. Recorded on
        # the unit and shouted in the window log, because the alternative is a silently
        # incomparable row in Table 13/14.
        stop = fold_stop_reason(partial)
        if stop:
            unit['convergence_reason'] = stop
            if stop == 'timeout':
                unit['note'] = ("WALL-CLOCK GUARD FIRED: stopped by the clock, not by "
                                "max_queries. Not comparable; investigate before use.")
                print(f"       !! wall-clock guard fired on {unit['id']}")
    else:
        unit['status'] = 'failed'
        unit['note'] = (f"exit={proc.returncode} partial_written={durable}; "
                        f"{(proc.stderr or '').strip()[-400:]}")
    write_ledger(ledger, ledger_path)
    return unit['status'] == 'done'


def acquire_window_lock(ledger_path: Path) -> Path | None:
    """Claim the right to run a window, or return None if one already is.

    Two windows on one ledger is not merely wasteful: the abandoned-unit reset
    treats anything marked running as dead, so a second window would reset the
    first's in-flight unit to pending and run it again — losing hours and writing
    two results for one unit. A belt-and-braces schedule alongside a manual launch
    makes that a live possibility rather than a theoretical one.

    A lock whose pid is gone is stale — a window killed by a closing lid leaves one —
    and is taken over rather than blocking the queue forever.
    """
    lock = ledger_path.with_suffix('.lock')
    if lock.exists():
        try:
            holder = json.loads(lock.read_text())
            pid = int(holder['pid'])
        except (json.JSONDecodeError, OSError, KeyError, ValueError):
            pid = None
        if pid is not None:
            try:
                os.kill(pid, 0)          # signal 0: liveness test, no signal sent
            except ProcessLookupError:
                print(f"  taking over a stale lock from dead pid {pid}")
            except PermissionError:
                print(f"  another window is running (pid {pid}, not ours) — exiting")
                return None
            else:
                print(f"  another window is already running (pid {pid}) — exiting cleanly")
                return None
    lock.write_text(json.dumps({'pid': os.getpid(), 'since': now()}))
    return lock


def cmd_run(args) -> int:
    ledger_path = Path(args.ledger)
    lock = acquire_window_lock(ledger_path)
    if lock is None:
        return 0                          # not an error: the work is already in hand
    try:
        return _run_window(args, ledger_path)
    finally:
        lock.unlink(missing_ok=True)


def _run_window(args, ledger_path: Path) -> int:
    ledger = load_ledger(ledger_path)
    remaining = parse_budget(args.budget)

    # A window killed at a boundary -- a closing lid, a SIGTERM -- leaves its unit
    # marked running with no process behind it, and nothing would ever pick it up
    # again. Only one window runs at a time, so anything still marked running when
    # a new one starts is by definition abandoned. Its partial, if it got that far,
    # is still on disk and run_cv will skip the fold.
    for unit in ledger['units']:
        if unit['status'] == 'running':
            unit['status'] = units_mod.STATUS_PENDING
            unit['note'] = f"reset from running: abandoned by a window that ended {unit['started_utc']}"
            print(f"  reset abandoned unit {unit['id']}")
    write_ledger(ledger, ledger_path)

    print(f"window budget {remaining:.2f} h   "
          f"multiplier {ledger['congen_multiplier'] or 'UNCALIBRATED'}   "
          f"safety x{ledger['safety_factor']}"
          + (f"   only={args.only}" if args.only else "")
          + (f"   reserve={args.reserve}" if args.reserve else ""))

    # Reservation, then backfill. A night window is sized for one busybox fold, and
    # if the queue were free to choose it would take the cheap units first and then
    # refuse busybox on the remainder -- silently, every night. So matching units are
    # offered the budget first, and only then is the rest of the queue released into
    # whatever is left. The tail of a night window is ~6 h that fits no second busybox
    # fold but plenty of QuAcq.
    def scan_order(units):
        if not args.reserve:
            return list(units)
        reserved = [u for u in units if args.reserve in u['id']]
        rest = [u for u in units if args.reserve not in u['id']]
        return reserved + rest

    ran = 0
    for unit in scan_order(ledger['units']):
        if unit['status'] != units_mod.STATUS_PENDING:
            continue
        if args.only and args.only not in unit['id']:
            continue
        cost = budgeted_cost(ledger, unit)
        if cost > remaining:
            print(f"  skip {unit['id']}: needs {cost:.2f} h, {remaining:.2f} h left")
            continue
        print(f"  run  {unit['id']} (estimate {unit['estimate_h']:.2f} h, "
              f"charged {cost:.2f} h)")
        if args.dry_run:
            remaining -= cost
            ran += 1
            continue
        ok = run_unit(ledger, unit, ledger_path, args.max_queries)
        remaining -= unit['actual_h']
        ran += 1
        print(f"       {'done' if ok else 'FAILED'} in {unit['actual_h']:.3f} h, "
              f"{remaining:.2f} h left")
        if not ok and args.stop_on_failure:
            print("  stopping: unit failed and --stop-on-failure is set")
            return 1
        if remaining <= 0:
            break

    print(f"window closed: {ran} units started, {remaining:.2f} h unspent")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--ledger', default=str(LEDGER))
    sub = parser.add_subparsers(dest='command', required=True)

    p_init = sub.add_parser('init', help='build the ledger')
    p_init.add_argument('--output-root', default=DEFAULT_OUTPUT_ROOT)
    p_init.add_argument('--force', action='store_true')
    p_init.set_defaults(func=cmd_init)

    sub.add_parser('status', help='what is done, what is left').set_defaults(func=cmd_status)

    p_re = sub.add_parser('reestimate',
                          help='refresh estimate_h from sweep_units, keeping progress')
    p_re.set_defaults(func=cmd_reestimate)

    p_run = sub.add_parser('run', help='work the queue for one window')
    p_run.add_argument('--budget', required=True, help="window budget, e.g. 5.5h")
    p_run.add_argument('--max-queries', type=int, default=5000,
                       help="QuAcq query cap (SoSyM revision doc, section 7 C1, decision 5)")
    p_run.add_argument('--reserve',
                       help="offer the budget to units whose id contains this substring "
                            "FIRST, then release the remainder to the rest of the queue. "
                            "Unlike --only this does not exclude anything: it fixes the "
                            "order so an expensive reserved unit cannot be crowded out by "
                            "cheap ones and then refused on what is left.")
    p_run.add_argument('--only',
                       help="run only units whose id contains this substring, e.g. "
                            "'busybox-1.18.0_ff'. Used to pull a decision-critical "
                            "measurement ahead of the cheapest-first order.")
    p_run.add_argument('--dry-run', action='store_true')
    p_run.add_argument('--stop-on-failure', action='store_true')
    p_run.set_defaults(func=cmd_run)

    args = parser.parse_args()
    return args.func(args)


if __name__ == '__main__':
    sys.exit(main())
