#!/usr/bin/env python
"""Re-run the ConGen sweep with NE passed to Reduce one constraint per e-.

Answers three questions that decide whether the per-e- split lands, and answers them
by MEASUREMENT rather than by predicting from the root-dependence classification --
the classification needs B' per fold, which costs the same as just running it. The
whole non-busybox ConGen sweep is 2.16 h of the ledger's 14.89 h, so predicting was
never the cheaper option.

  1. n_ne per fold. Under the combined encoding n_ne in {0,1} -- the premise C6 was
     decided on. Split per e-, |KB| = n_kb + n_ne rises by however many memorized
     facts the KB does not entail.
  2. |KB| delta against the committed run, per knowledge base.
  3. Whether accuracy moves. exact_equiv needs a separate scoring pass over the CV
     files this writes (make_score_configs.py -> run_compare).

Writes ONLY under --out. data/results_sosym is never touched; run_cv's own guard
refuses the default path, and this passes -o unconditionally.

    measure_ne_per_example.py --out <scratch>              # 24 cells, ~2.2 h
    measure_ne_per_example.py --out <scratch> --kbs fqa    # one KB
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

# busybox is 12.73 h of the 14.89 h ConGen sweep and belongs in a night window.
STEMS = ['REAL-FM-7', 'arcade-game', 'fqa', 'REAL-FM-4']
SAMPLINGS = ['rs_1n', 'rs_2n', 'rs_3n', 'rs_m', 'ff', '2cov']

CONFIG = """# Generated by apps/sosym_r1/measure_ne_per_example.py -- do not edit by hand.
[general]
seed = 42
output_dir = "MEASURE_ALWAYS_PASSES_-o"
verbose = false

[evaluation]
algorithm = "congen"
n_folds = 3
solver_name = "glucose4"
solver_mode = "incremental"
shuffle_bias = true

[[models]]
name = "{model}"
oracle = "data/fms/{stem}.uvl"
bias = "data/bias/{stem}-bias.json"
examples = "data/examples/{model}.json"
folds_path = "data/folds/{model}_folds.json"
"""


def committed_folds(model: str) -> list | None:
    path = REPO / 'data' / 'results_sosym' / 'congen' / f'{model}_cv_incremental.json'
    if not path.exists():
        return None
    return json.loads(path.read_text())['folds']


def run_cell(out_root: Path, stem: str, sampling: str) -> dict | None:
    model = f'{stem}_{sampling}'
    if not (REPO / 'data' / 'examples' / f'{model}.json').exists():
        print(f"  SKIP {model}: no example set")
        return None
    cell = out_root / model
    cell.mkdir(parents=True, exist_ok=True)
    (cell / 'config.toml').write_text(CONFIG.format(model=model, stem=stem))

    started = time.time()
    proc = subprocess.run(
        [sys.executable, '-m', 'apps.run_cv', str(cell / 'config.toml'),
         '-o', str(cell)],
        cwd=REPO, capture_output=True, text=True)
    elapsed = time.time() - started

    result = cell / 'congen' / f'{model}_cv_incremental.json'
    if proc.returncode != 0 or not result.exists():
        print(f"  FAILED {model} exit={proc.returncode}: "
              f"{(proc.stderr or '').strip()[-300:]}")
        return None

    new = json.loads(result.read_text())['folds']
    old = committed_folds(model)
    rows = []
    for i, f in enumerate(new):
        s = f['statistics']
        o = old[i]['statistics'] if old and i < len(old) else {}
        rows.append({
            'fold': f['fold_index'],
            'train_neg': f['train_size']['negative'],
            'n_kb': s['n_kb'], 'n_ne': s.get('n_ne', 0),
            'red_ne': len(f.get('redundant_ne_constraints', [])),
            'old_n_kb': o.get('n_kb'), 'old_n_ne': o.get('n_ne'),
            'accuracy': f.get('accuracy'), 'old_accuracy': old[i].get('accuracy') if old else None,
        })
    return {'model': model, 'kb': stem, 'sampling': sampling,
            'wall_s': round(elapsed, 1), 'folds': rows}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--out', required=True)
    ap.add_argument('--kbs', nargs='+', default=STEMS)
    ap.add_argument('--samplings', nargs='+', default=SAMPLINGS)
    args = ap.parse_args()

    out_root = Path(args.out)
    out_root.mkdir(parents=True, exist_ok=True)
    cells = []
    for stem in args.kbs:
        for sampling in args.samplings:
            print(f"  {stem}_{sampling} ...", flush=True)
            row = run_cell(out_root, stem, sampling)
            if row:
                cells.append(row)
                for r in row['folds']:
                    print(f"    fold{r['fold']} E-={r['train_neg']:<4} "
                          f"n_kb {r['old_n_kb']}->{r['n_kb']}  "
                          f"n_ne {r['old_n_ne']}->{r['n_ne']} (+{r['red_ne']} discarded)  "
                          f"acc {r['old_accuracy']}->{r['accuracy']}", flush=True)
            (out_root / 'ne-split-results.json').write_text(json.dumps(cells, indent=2))

    print(f"\n=== |KB| = n_kb + n_ne, per knowledge base ===")
    print(f"{'kb':14}{'folds':>6}{'old |KB|':>10}{'new |KB|':>10}{'d|KB|':>8}"
          f"{'old n_ne':>10}{'new n_ne':>10}{'acc moved':>11}")
    for stem in args.kbs:
        rs = [r for c in cells if c['kb'] == stem for r in c['folds']
              if r['old_n_kb'] is not None]
        if not rs:
            continue
        old = sum(r['old_n_kb'] + (r['old_n_ne'] or 0) for r in rs)
        new = sum(r['n_kb'] + r['n_ne'] for r in rs)
        moved = sum(1 for r in rs if r['accuracy'] != r['old_accuracy'])
        print(f"{stem:14}{len(rs):>6}{old:>10}{new:>10}{new - old:>+8}"
              f"{sum(r['old_n_ne'] or 0 for r in rs):>10}"
              f"{sum(r['n_ne'] for r in rs):>10}{moved:>7}/{len(rs)}")
    print(f"\nwritten to {out_root / 'ne-split-results.json'}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
