#!/usr/bin/env python
"""Measure what the QuAcq query cap buys, and what it costs.

Two questions, and they are different. Whether raising the cap changes the learned
theory is a paper result: if the knowledge base is the same at 1,000 and at 5,000,
the active baseline is not being starved, which answers the starvation question
better than a larger number would. What raising it costs is a scheduling input.

So this reports, per (kb, sampling, mode, cap):
  - the learned constraint SET per fold, compared element-wise across caps.
    Counts are not enough: two different 2-constraint theories have the same size
    and different semantic F1.
  - wall-clock and queries consumed, as a curve over caps rather than one ratio,
    because the interesting quantity is how marginal cost grows with budget.

Every run goes to a scratch directory via -o. Run it uncontended: it is a timing
measurement, and a sweep window on another core invalidates it.

    probe_query_budget.py --out <scratch> [--kbs arcade-game REAL-FM-4]
                          [--caps 250 500 1000 2000 5000] [--modes example_first]
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

CONFIG = """# Generated by probe_query_budget.py
[general]
seed = 42
output_dir = "PROBE_ALWAYS_PASSES_-o"
verbose = false

[evaluation]
algorithm = "interactive"
n_folds = 3
solver_name = "glucose4"
solver_mode = "incremental"
shuffle_bias = true

[evaluation.interactive]
max_queries = {cap}
timeout_s = {timeout_s}
query_mode = "{mode}"

[[models]]
name = "{model}"
oracle = "data/fms/{stem}.uvl"
bias = "data/bias/{stem}-bias.json"
examples = "data/examples/{model}.json"
folds_path = "data/folds/{model}_folds.json"
"""


def constraint_names(fold: dict) -> set:
    """Learned constraint identities, however the fold happens to serialize them."""
    out = set()
    for c in fold.get('kb_constraints', []):
        if isinstance(c, str):
            out.add(c)
        else:
            out.add(c.get('name') or c.get('id') or json.dumps(c, sort_keys=True))
    return out


def run_cell(out_root: Path, stem: str, sampling: str, mode: str, cap: int,
             timeout_s: int) -> dict | None:
    model = f"{stem}_{sampling}"
    cell_dir = out_root / f"{model}_{mode}_cap{cap}"
    cell_dir.mkdir(parents=True, exist_ok=True)
    config = cell_dir / 'config.toml'
    config.write_text(CONFIG.format(cap=cap, mode=mode, model=model, stem=stem,
                                    timeout_s=timeout_s))

    started = time.time()
    proc = subprocess.run(
        [sys.executable, '-m', 'apps.run_cv', str(config), '-o', str(cell_dir)],
        cwd=REPO, capture_output=True, text=True)
    elapsed = time.time() - started

    result = cell_dir / 'interactive' / f"{model}_cv_incremental_{mode}.json"
    if proc.returncode != 0 or not result.exists():
        print(f"    FAILED exit={proc.returncode}: {(proc.stderr or '').strip()[-200:]}")
        return None

    data = json.loads(result.read_text())
    return {
        'kb': stem, 'sampling': sampling, 'mode': mode, 'cap': cap,
        'wall_s': round(elapsed, 2),
        'queries': [f.get('n_queries') for f in data['folds']],
        'stop': [f.get('convergence_reason') for f in data['folds']],
        'n_kb': [f['statistics']['n_kb'] for f in data['folds']],
        'sets': [sorted(constraint_names(f)) for f in data['folds']],
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--out', required=True)
    ap.add_argument('--kbs', nargs='+', default=['arcade-game', 'REAL-FM-4'])
    ap.add_argument('--sampling', default='rs_1n')
    ap.add_argument('--modes', nargs='+', default=['example_first', 'example_only'])
    ap.add_argument('--caps', nargs='+', type=int, default=[250, 500, 1000, 2000, 5000])
    ap.add_argument('--timeout-s', type=int, default=6 * 3600)
    ap.add_argument('--budget-h', type=float,
                    help="stop starting new cells once this many hours have elapsed. "
                         "Without it the probe runs every cell to completion however "
                         "long that takes, which is how a bounded 13 h night window "
                         "ran for 13 h 40 m and was still going in the morning.")
    args = ap.parse_args()
    started_at = time.time()

    out_root = Path(args.out)
    out_root.mkdir(parents=True, exist_ok=True)
    rows = []

    def budget_spent() -> bool:
        """True once the probe's share of the night is gone.

        Checked before starting a cell, never during one: a cell killed part-way is a
        cell whose whole cost is wasted, and cells are the unit that checkpoints.
        """
        if args.budget_h is None:
            return False
        return (time.time() - started_at) / 3600 >= args.budget_h

    for stem in args.kbs:
        if budget_spent():
            break
        for mode in args.modes:
            if budget_spent():
                break
            for cap in sorted(args.caps):
                if budget_spent():
                    spent = (time.time() - started_at) / 3600
                    print(f"  budget {args.budget_h} h spent ({spent:.2f} h); "
                          f"stopping before {stem} {mode} cap={cap}", flush=True)
                    break
                print(f"  {stem} {args.sampling} {mode} cap={cap} ...", flush=True)
                row = run_cell(out_root, stem, args.sampling, mode, cap, args.timeout_s)
                if row:
                    rows.append(row)
                    print(f"    {row['wall_s']:8.1f} s  queries={row['queries']}  "
                          f"n_kb={row['n_kb']}  stop={sorted(set(row['stop']))}")
                (out_root / 'probe-results.json').write_text(json.dumps(rows, indent=2))

    print("\n=== SET EQUALITY vs the largest cap, per fold ===")
    for stem in args.kbs:
        for mode in args.modes:
            cells = sorted([r for r in rows if r['kb'] == stem and r['mode'] == mode],
                           key=lambda r: r['cap'])
            if len(cells) < 2:
                continue
            top = cells[-1]
            for r in cells[:-1]:
                verdicts = []
                for i, (a, b) in enumerate(zip(r['sets'], top['sets'])):
                    verdicts.append('=' if set(a) == set(b) else '≠')
                print(f"  {stem:14s} {mode:14s} cap {r['cap']:>5d} vs {top['cap']:>5d}: "
                      f"{' '.join(verdicts)}")
                for i, (a, b) in enumerate(zip(r['sets'], top['sets'])):
                    if set(a) != set(b):
                        print(f"      fold {i} only@{r['cap']}: {sorted(set(a)-set(b))}")
                        print(f"      fold {i} only@{top['cap']}: {sorted(set(b)-set(a))}")

    print("\n=== COST CURVE: wall-clock and marginal cost per query ===")
    print(f"{'kb':14s}{'mode':14s}{'cap':>6s}{'wall_s':>10s}{'x vs 1000':>11s}"
          f"{'ms/query':>10s}")
    for stem in args.kbs:
        for mode in args.modes:
            cells = sorted([r for r in rows if r['kb'] == stem and r['mode'] == mode],
                           key=lambda r: r['cap'])
            base = next((c for c in cells if c['cap'] == 1000), None)
            for r in cells:
                q = sum(x for x in r['queries'] if x) or 1
                rel = f"{r['wall_s']/base['wall_s']:.2f}" if base and base['wall_s'] else "-"
                print(f"{stem:14s}{mode:14s}{r['cap']:>6d}{r['wall_s']:>10.1f}{rel:>11s}"
                      f"{r['wall_s']*1000/q:>10.1f}")

    print(f"\nrows written to {out_root / 'probe-results.json'}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
