#!/usr/bin/env python
"""Re-run the committed ConGen sweep with RAW negative examples (no oracle in GenerateNE).

GenerateNE's default reduces each e⁻ to a subset-minimal conflict with QuickXplain
against the target KB -- an oracle call. ``[evaluation.congen] neg_mode = "raw"``
negates the full e⁻ instead. This reruns every cell of data/results_sosym_r1/congen/
under raw and changes NOTHING else: same examples, folds, seed, solver, solver mode
and per-fold bias shuffle as tools/sosym_r1/sweep_queue.py's CONFIG_TEMPLATE, and one
process per fold, as the sweep ran it (memory_peak_mb depends on a fold's position in
its process).

Cells run sequentially, cheapest first, busybox last (it is ~12.7 h of the ~15 h).
Nothing else heavy should run beside it: runtime is one of the compared quantities.
A fold whose partial is already on disk is skipped by run_cv itself, so an interrupted
sweep resumes by running the same command again.

Writes ONLY under --out. The frozen results tree is refused by path.

    run_ne_raw_sweep.py --out data/results_sosym_r1_rawne
    run_ne_raw_sweep.py --out <dir> --kbs REAL-FM-7 --samplings ff
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
FROZEN = REPO / 'data' / 'results_sosym_r1'
N_FOLDS = 3

# Cheapest first; busybox last and in its own cost order. Exactly the 28 committed
# cells: busybox rs_2n / rs_3n were never run (frozen.py declares them not-run).
CELLS = ([(s, p) for s in ('REAL-FM-7', 'fqa', 'arcade-game', 'REAL-FM-4')
          for p in ('2cov', 'rs_m', 'ff', 'rs_1n', 'rs_2n', 'rs_3n')]
         + [('busybox-1.18.0', p) for p in ('2cov', 'rs_m', 'ff', 'rs_1n')])

CONFIG = """# Generated by apps/sosym_r1/run_ne_raw_sweep.py -- do not edit by hand.
# Identical to tools/sosym_r1/sweep_queue.py's CONFIG_TEMPLATE for a congen unit,
# plus [evaluation.congen] neg_mode.
[general]
seed = 42
output_dir = "RAW_SWEEP_ALWAYS_PASSES_-o"
verbose = false

[evaluation]
algorithm = "congen"
n_folds = {n_folds}
solver_name = "glucose4"
solver_mode = "incremental"
shuffle_bias = true

[evaluation.congen]
neg_mode = "{neg_mode}"

[[models]]
name = "{model}"
oracle = "data/fms/{stem}.uvl"
bias = "data/bias/{stem}-bias.json"
examples = "data/examples/{model}.json"
folds_path = "data/folds/{model}_folds.json"
"""


def now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec='seconds')


def commit() -> str:
    return subprocess.run(['git', 'rev-parse', 'HEAD'], cwd=REPO, capture_output=True,
                          text=True, check=True).stdout.strip()


def run_cell(out: Path, stem: str, sampling: str, neg_mode: str, ledger: Path) -> bool:
    model = f'{stem}_{sampling}'
    if not (FROZEN / 'congen' / f'{model}_cv_incremental.json').exists():
        print(f'  SKIP {model}: no committed reduced result to compare against')
        return True
    config = out / 'configs' / f'congen_{model}.toml'
    config.parent.mkdir(parents=True, exist_ok=True)
    config.write_text(CONFIG.format(n_folds=N_FOLDS, neg_mode=neg_mode,
                                    model=model, stem=stem))
    partials = out / 'congen' / 'partials'
    ok = True
    for fold in range(N_FOLDS):
        if (partials / f'{model}_incremental_fold{fold}.json').exists():
            print(f'  {model} fold {fold}: partial on disk, skipped', flush=True)
            continue
        started, t0 = now(), time.time()
        proc = subprocess.run(
            [sys.executable, '-m', 'apps.run_cv', str(config), '-o', str(out),
             '--folds', str(fold)], cwd=REPO, capture_output=True, text=True)
        wall = time.time() - t0
        row = {'model': model, 'fold': fold, 'neg_mode': neg_mode, 'exit': proc.returncode,
               'wall_s': round(wall, 1), 'started_utc': started,
               'finished_utc': now(), 'commit': commit()}
        with ledger.open('a') as fh:
            fh.write(json.dumps(row) + '\n')
        print(f'  {model} fold {fold}: exit {proc.returncode}, {wall:.1f} s', flush=True)
        if proc.returncode != 0:
            print((proc.stderr or '').strip()[-600:], file=sys.stderr)
            ok = False
            break
    return ok


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--out', required=True)
    ap.add_argument('--neg-mode', default='raw', choices=('raw', 'reduced'))
    ap.add_argument('--kbs', nargs='+')
    ap.add_argument('--samplings', nargs='+')
    args = ap.parse_args()

    out = Path(args.out).resolve()
    if out == FROZEN.resolve() or FROZEN.resolve() in out.parents:
        print(f'refusing to write into the frozen tree {FROZEN}', file=sys.stderr)
        return 2
    out.mkdir(parents=True, exist_ok=True)
    ledger = out / 'run-ledger.jsonl'

    cells = [(s, p) for s, p in CELLS
             if (not args.kbs or s in args.kbs)
             and (not args.samplings or p in args.samplings)]
    print(f'{len(cells)} cells, neg_mode={args.neg_mode}, out={out}', flush=True)
    failed = [f'{s}_{p}' for s, p in cells
              if not run_cell(out, s, p, args.neg_mode, ledger)]
    if failed:
        print(f'FAILED: {failed}', file=sys.stderr)
        return 1
    print('done', flush=True)
    return 0


if __name__ == '__main__':
    sys.exit(main())
