"""Layer 1 of the T11 oracle safety net — interaction trace record & replay.

The oracle's observable surface is small and T11 touches only the oracle (not the
algorithms). So if the refactored oracle answers every frozen query identically
and every pre-query getter matches, the whole system is identical *by
construction* — the strongest net available, and independent of the RNG.

Goldens (``fixtures/t11_oracle_net/{queries,trace}_<fm>.json``) were recorded from
the CURRENT oracle by ``scripts/build_t11_oracle_net_fixtures.py`` and are frozen.
This test only READS them — it never regenerates the queries or the answers (a
golden whose inputs are regenerated by the code under test proves nothing).

get_c/get_kb/get_assumptions/get_bg_data are pinned from a snapshot taken BEFORE
any query, so this layer never encodes the A6 last-query pollution of get_c —
that intended change is pinned separately (as an xfail) in the guard suite.
"""
import pytest

from conacq.oracle import FMOracle
from tests.t11_oracle_net_helpers import (
    FM_SPECS,
    canonical_snapshot,
    load_json,
    queries_path,
    replay_answers,
    trace_path,
)


def _params():
    params = []
    for name, path, slow, _n, _m in FM_SPECS:
        marks = [pytest.mark.slow] if slow else []
        params.append(pytest.param(name, path, id=name, marks=marks))
    return params


@pytest.mark.parametrize("name,path", _params())
def test_oracle_trace_replays_exactly(name, path):
    q_path, t_path = queries_path(name), trace_path(name)
    if not q_path.exists() or not t_path.exists():
        # A missing committed golden means the net is NOT running — that must be
        # red, never a silent skip (a skipped net reads as "covered" when it isn't).
        pytest.fail(
            f"golden fixture missing for {name} — the net is NOT running; "
            f"run PYTHONPATH=. python3 scripts/build_t11_oracle_net_fixtures.py "
            f"--include-slow"
        )
    queries = load_json(q_path)
    golden = load_json(t_path)

    oracle = FMOracle(str(path))

    # (1) Every observable getter, snapshotted before any query, must match.
    assert canonical_snapshot(oracle) == golden["snapshot"]

    # (2) Every membership answer and every completion must match exactly.
    answers = replay_answers(oracle, queries)
    membership_golden = golden["answers"]["membership"]
    # Pinpoint the first divergence if any — a single bool flip is a broken oracle.
    first_flip = next(
        (i for i, (a, b) in enumerate(zip(answers["membership"], membership_golden))
         if a != b),
        None,
    )
    assert first_flip is None, (
        f"{name}: membership answer diverged at query #{first_flip} "
        f"(golden={membership_golden[first_flip]}, got={answers['membership'][first_flip]})"
    )
    assert answers["membership"] == membership_golden
    assert answers["completion"] == golden["answers"]["completion"]
