#!/usr/bin/env python3
"""Render data/bias-config/README.md from the YAML configs beside it.

    python3 apps/describe_bias_configs.py            # rewrite the README
    python3 apps/describe_bias_configs.py --check    # fail if it has drifted

WHY THIS IS GENERATED
---------------------
The README used to be a captured console log of `apps/generate_bias_config.py`. A log
records what one run printed, which stops being true the moment a config is
regenerated with different settings — and it did. It logged `Cross-tree mode: all`
for REAL-FM-4, fqa and arcade-game while their YAML said `extracted`, so a reader
consulting it would have concluded the evaluation paired every feature on three
models where it pairs 34, 14 and 34. The built biases agreed with the YAML, not with
the log, so nothing else in the repository disagreed with itself and nothing caught it.

Every column below is therefore read from the YAML at render time, and
`scripts/check-release-hygiene.sh` re-renders and compares before a carve is
published. A description that can only be right is better than one that has to be
remembered.

WHAT IS NOT HERE, AND WHY
-------------------------
The old log also printed the number of cross-tree constraints in the original feature
model. That is a property of the .uvl, not of the config, and the config keeps it only
in a YAML comment that no parser reads. Deriving it would mean parsing comments, which
is how a generated file starts being wrong again; read it from `data/fms/` instead.
"""
from __future__ import annotations

import argparse
import difflib
import math
import sys
from pathlib import Path

import yaml

from conacq.atomic_io import write_text_atomic

REPO = Path(__file__).resolve().parents[1]
CONFIG_DIR = REPO / 'data' / 'bias-config'
ABSENT = 'n/a'

HEADER = """<!-- GENERATED by apps/describe_bias_configs.py from the YAML files beside it.
     Do not edit by hand: the next render overwrites it, and a hand-edited value is
     exactly the drift this file is generated to prevent. -->

# Bias configurations

One YAML per feature model, produced by `apps/generate_bias_config.py` from the
matching `data/fms/<name>.uvl`, and consumed by `apps/generate_bias_files.py` to build
`data/bias/<name>-bias.json`. A config declares the candidate constraints the
acquisition may choose from: the hierarchical relationships of the feature tree, and
which feature pairs are admitted to cross-tree candidates.

`cross_tree_mode` decides the second part. `all` pairs every feature; `extracted` pairs
only the features that appear in the model's own cross-tree constraints, and `k` below
is how many that leaves. The quadratic term is driven by `k`, not by the feature count,
which is why `|B|` does not track model size.

Each row is read from the YAML itself:

  binary / group     entries of `hierarchical_candidates` by `relationship_type`
  k                  `cross_tree_candidates.cross_tree_features`, or every feature
                     when the mode is `all`
  |B|                2 (binary + group) + 3 C(k, 2), the size the config implies

`|B|` is what the built bias must contain; `data/bias/<name>-bias-stats.txt` reports
what it does contain, and the two are asserted equal for the five evaluated models.
"""

FOOTER = """
`{name}` has no `leaf_features` key: it is a hand-written illustration of the format
rather than a config generated from a feature model.
"""

# (key in a described row, column header). The header for the bias size escapes its
# pipes: an unescaped `|B|` inside a cell ends the cell, and the table renders with two
# stray columns everywhere a reader looks at it.
COLUMNS = (('model', 'model'), ('features', 'features'), ('leaf', 'leaf'),
           ('binary', 'binary'), ('group', 'group'), ('mode', 'mode'),
           ('k', 'k'), ('bias', r'\|B\|'))


def describe(path: Path) -> dict:
    """One config, as the numbers a reader needs and nothing else."""
    cfg = yaml.safe_load(path.read_text())
    features = cfg['features']
    hierarchical = cfg.get('hierarchical_candidates') or []
    cross = cfg.get('cross_tree_candidates') or {}
    extracted = cross.get('cross_tree_features')
    leaves = cfg.get('leaf_features')
    binary = sum(1 for h in hierarchical if h.get('relationship_type') == 'binary')
    group = sum(1 for h in hierarchical if h.get('relationship_type') == 'group')
    k = len(extracted) if extracted else len(features)
    return {
        # The file stem, not the YAML's `name`: the stem is what pairs a config with
        # data/bias/<stem>-bias.json, and survey_example.yaml calls itself `Survey`.
        'model': path.stem,
        'features': len(features),
        'leaf': len(leaves) if leaves is not None else None,
        'binary': binary,
        'group': group,
        'mode': cross.get('cross_tree_mode') or ABSENT,
        'k': k,
        'bias': 2 * (binary + group) + 3 * math.comb(k, 2),
    }


def cell(row: dict, key: str) -> str:
    value = row[key]
    if value is None:
        return ABSENT
    return f'{value:,}' if isinstance(value, int) else str(value)


def render(rows: list[dict]) -> str:
    """The README, byte-stable for a given set of configs."""
    headers = [h for _k, h in COLUMNS]
    table = [[cell(r, k) for k, _h in COLUMNS] for r in rows]
    widths = [max(len(headers[i]), *(len(r[i]) for r in table)) for i in range(len(COLUMNS))]
    # Model and mode read left to right; every count is a magnitude, so it is right-aligned.
    align = ['<' if k in ('model', 'mode') else '>' for k, _h in COLUMNS]

    def line(cells: list[str]) -> str:
        return '| ' + ' | '.join(f'{c:{a}{w}}' for c, a, w in zip(cells, align, widths)) + ' |'

    rule = '|' + '|'.join('-' * (w + 2) for w in widths) + '|'
    body = '\n'.join([line(headers), rule, *(line(r) for r in table)])

    text = HEADER + '\n' + body + '\n'
    handwritten = [r['model'] for r in rows if r['leaf'] is None]
    for name in handwritten:
        text += FOOTER.format(name=name)
    return text


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--check', action='store_true',
                        help='compare instead of writing; exit 1 if the README has drifted')
    parser.add_argument('--config-dir', default=str(CONFIG_DIR),
                        help='the directory holding the YAML configs and the README')
    args = parser.parse_args()

    config_dir = Path(args.config_dir)
    configs = sorted(config_dir.glob('*.yaml'))
    # A positive count, never the absence of an error: an empty directory would
    # otherwise render an empty table and report it as agreement.
    if not configs:
        print(f'FAIL: no bias configs under {config_dir}', file=sys.stderr)
        return 1

    want = render([describe(p) for p in configs])
    readme = config_dir / 'README.md'

    if not args.check:
        write_text_atomic(readme, want)
        print(f'{readme} rendered from {len(configs)} config(s)')
        return 0

    got = readme.read_text() if readme.exists() else ''
    if got == want:
        print(f'  ok: {readme.name} agrees with the {len(configs)} config(s) beside it')
        return 0
    print(f'  {readme} has drifted from the YAML configs it describes.', file=sys.stderr)
    print('  Re-render it: python3 apps/describe_bias_configs.py', file=sys.stderr)
    for diff in list(difflib.unified_diff(got.splitlines(), want.splitlines(),
                                          'committed', 'rendered', lineterm=''))[:40]:
        print(f'    {diff}', file=sys.stderr)
    return 1


if __name__ == '__main__':
    raise SystemExit(main())
